#!/usr/bin/env node
import fs from "node:fs/promises"

const styles = [
  "naturalearth-openmaptiles/cartodb/dark-matter/style.json",
  "naturalearth-openmaptiles/cartodb/positron/style.json",
  "naturalearth-openmaptiles/cartodb/voyager/style.json",
  "naturalearth-openmaptiles/maps.black/hybrid-2016/style.json",
  "naturalearth-openmaptiles/maps.black/hybrid-2023/style.json",
  "naturalearth-openmaptiles/maputnik/liberty/style.json",
  "naturalearth-openmaptiles/nst-guide/liberty-topo/style.json",
  "naturalearth-openmaptiles/openfreemap/bright/style.json",
  "naturalearth-openmaptiles/openfreemap/dark/style.json",
  "naturalearth-openmaptiles/openfreemap/fiord/style.json",
  "naturalearth-openmaptiles/openfreemap/liberty/style.json",
  "naturalearth-openmaptiles/openfreemap/positron/style.json",
  "naturalearth-openmaptiles/openmaptiles/basic/style.json",
  "naturalearth-openmaptiles/openmaptiles/bright/style.json",
  "naturalearth-openmaptiles/openmaptiles/dark-matter/style.json",
  "naturalearth-openmaptiles/openmaptiles/fiord/style.json",
  "naturalearth-openmaptiles/openmaptiles/maptiler-3d/style.json",
  "naturalearth-openmaptiles/openmaptiles/openmaptiles/style.json",
  "naturalearth-openmaptiles/openmaptiles/positron/style.json",
  "naturalearth-openmaptiles/openmaptiles/terrain/style.json",
  "naturalearth-openmaptiles/openmaptiles/toner/style.json",
  "naturalearth-openmaptiles/osm-americana/americana/style.json",
  "naturalearth-openmaptiles/qwant/basic/style.json",
  "naturalearth-protomaps/maps.black/hybrid-2016/style.json",
  "naturalearth-protomaps/maps.black/hybrid-2023/style.json",
  "naturalearth-protomaps/protomaps/bio/style.json",
  "naturalearth-protomaps/protomaps/black_and_white/style.json",
  "naturalearth-protomaps/protomaps/black/style.json",
  "naturalearth-protomaps/protomaps/dark/style.json",
  "naturalearth-protomaps/protomaps/dusk_rose/style.json",
  "naturalearth-protomaps/protomaps/grayscale/style.json",
  "naturalearth-protomaps/protomaps/iris_bloom/style.json",
  "naturalearth-protomaps/protomaps/light/style.json",
  "naturalearth-protomaps/protomaps/rainforest/style.json",
  "naturalearth-protomaps/protomaps/seafoam/style.json",
  "naturalearth-protomaps/protomaps/white/style.json",
  "naturalearth-shortbread/maps.black/hybrid-2016/style.json",
  "naturalearth-shortbread/maps.black/hybrid-2023/style.json",
  "naturalearth-shortbread/versatiles/colorful/style.json",
  "naturalearth-shortbread/versatiles/eclipse/style.json",
  "naturalearth-shortbread/versatiles/graybeard/style.json",
  "naturalearth-shortbread/versatiles/neutrino/style.json",
  "openstreetmap-openmaptiles/cartodb/dark-matter/style.json",
  "openstreetmap-openmaptiles/cartodb/positron/style.json",
  "openstreetmap-openmaptiles/cartodb/voyager/style.json",
  "openstreetmap-openmaptiles/maps.black/hybrid-2016/style.json",
  "openstreetmap-openmaptiles/maps.black/hybrid-2023/style.json",
  "openstreetmap-openmaptiles/maputnik/liberty/style.json",
  "openstreetmap-openmaptiles/nst-guide/liberty-topo/style.json",
  "openstreetmap-openmaptiles/openfreemap/bright/style.json",
  "openstreetmap-openmaptiles/openfreemap/dark/style.json",
  "openstreetmap-openmaptiles/openfreemap/fiord/style.json",
  "openstreetmap-openmaptiles/openfreemap/liberty/style.json",
  "openstreetmap-openmaptiles/openfreemap/positron/style.json",
  "openstreetmap-openmaptiles/openmaptiles/basic/style.json",
  "openstreetmap-openmaptiles/openmaptiles/bright/style.json",
  "openstreetmap-openmaptiles/openmaptiles/dark-matter/style.json",
  "openstreetmap-openmaptiles/openmaptiles/fiord/style.json",
  "openstreetmap-openmaptiles/openmaptiles/maptiler-3d/style.json",
  "openstreetmap-openmaptiles/openmaptiles/openmaptiles/style.json",
  "openstreetmap-openmaptiles/openmaptiles/positron/style.json",
  "openstreetmap-openmaptiles/openmaptiles/terrain/style.json",
  "openstreetmap-openmaptiles/openmaptiles/toner/style.json",
  "openstreetmap-openmaptiles/osm-americana/americana/style.json",
  "openstreetmap-openmaptiles/qwant/basic/style.json",
  "openstreetmap-protomaps/maps.black/hybrid-2016/style.json",
  "openstreetmap-protomaps/maps.black/hybrid-2023/style.json",
  "openstreetmap-protomaps/protomaps/bio/style.json",
  "openstreetmap-protomaps/protomaps/black_and_white/style.json",
  "openstreetmap-protomaps/protomaps/black/style.json",
  "openstreetmap-protomaps/protomaps/dark/style.json",
  "openstreetmap-protomaps/protomaps/dusk_rose/style.json",
  "openstreetmap-protomaps/protomaps/grayscale/style.json",
  "openstreetmap-protomaps/protomaps/iris_bloom/style.json",
  "openstreetmap-protomaps/protomaps/light/style.json",
  "openstreetmap-protomaps/protomaps/rainforest/style.json",
  "openstreetmap-protomaps/protomaps/seafoam/style.json",
  "openstreetmap-protomaps/protomaps/white/style.json",
  "openstreetmap-shortbread/maps.black/hybrid-2016/style.json",
  "openstreetmap-shortbread/maps.black/hybrid-2023/style.json",
  "openstreetmap-shortbread/versatiles/colorful/style.json",
  "openstreetmap-shortbread/versatiles/eclipse/style.json",
  "openstreetmap-shortbread/versatiles/graybeard/style.json",
  "openstreetmap-shortbread/versatiles/neutrino/style.json",
  "raster/naturalearth6/GRAY_HR_DARK_OB_DR-WEBP/style.json",
  "raster/naturalearth6/GRAY_HR_DARK_W_DR-WEBP/style.json",
  "raster/naturalearth6/GRAY_HR_DARK-WEBP/style.json",
  "raster/naturalearth6/GRAY_HR_DARK_W-WEBP/style.json",
  "raster/naturalearth6/GRAY_HR_LIGHT_OB_DR-WEBP/style.json",
  "raster/naturalearth6/GRAY_HR_LIGHT_W_DR-WEBP/style.json",
  "raster/naturalearth6/GRAY_HR_LIGHT-WEBP/style.json",
  "raster/naturalearth6/GRAY_HR_LIGHT_W-WEBP/style.json",
  "raster/naturalearth6/HYP_HR_SR_OB_DR-WEBP/style.json",
  "raster/naturalearth6/HYP_HR_SR_OB-WEBP/style.json",
  "raster/naturalearth6/HYP_HR_SR_W_DR-WEBP/style.json",
  "raster/naturalearth6/HYP_HR_SR-WEBP/style.json",
  "raster/naturalearth6/HYP_HR_SR_W-WEBP/style.json",
  "raster/naturalearth6/HYP_HR-WEBP/style.json",
  "raster/naturalearth6/LC_HR_HD-WEBP/style.json",
  "raster/naturalearth6/NE1_HR_SR_OB_DR-WEBP/style.json",
  "raster/naturalearth6/NE1_HR_SR_OB-WEBP/style.json",
  "raster/naturalearth6/NE1_HR_SR_W_DR-WEBP/style.json",
  "raster/naturalearth6/NE1_HR_SR-WEBP/style.json",
  "raster/naturalearth6/NE1_HR_SR_W-WEBP/style.json",
  "raster/naturalearth6/NE1_HR-WEBP/style.json",
  "raster/naturalearth6/NE2_HR_SR_OB_DR-WEBP/style.json",
  "raster/naturalearth6/NE2_HR_SR_OB-WEBP/style.json",
  "raster/naturalearth6/NE2_HR_SR_W_DR-WEBP/style.json",
  "raster/naturalearth6/NE2_HR_SR-WEBP/style.json",
  "raster/naturalearth6/NE2_HR_SR_W-WEBP/style.json",
  "raster/naturalearth6/NE2_HR-WEBP/style.json",
  "raster/naturalearth6/OB_HR_DARK-WEBP/style.json",
  "raster/naturalearth6/OB_HR_LIGHT-WEBP/style.json",
  "raster/naturalearth6/SR_HR_UD-WEBP/style.json",
  "raster/naturalearth/GRAY_HR_SR_OB_DR-WEBP/style.json",
  "raster/naturalearth/GRAY_HR_SR_OB-WEBP/style.json",
  "raster/naturalearth/GRAY_HR_SR-WEBP/style.json",
  "raster/naturalearth/GRAY_HR_SR_W-WEBP/style.json",
  "raster/naturalearth/HYP_HR_SR_OB_DR-WEBP/style.json",
  "raster/naturalearth/HYP_HR_SR_W_DR-WEBP/style.json",
  "raster/naturalearth/HYP_HR_SR-WEBP/style.json",
  "raster/naturalearth/HYP_HR_SR_W-WEBP/style.json",
  "raster/naturalearth/HYP_HR-WEBP/style.json",
  "raster/naturalearth/NE1_HR_LC_SR_W_DR-WEBP/style.json",
  "raster/naturalearth/NE1_HR_LC_SR-WEBP/style.json",
  "raster/naturalearth/NE1_HR_LC_SR_W-WEBP/style.json",
  "raster/naturalearth/NE1_HR_LC-WEBP/style.json",
  "raster/naturalearth/NE2_HR_LC_SR_W_DR-WEBP/style.json",
  "raster/naturalearth/NE2_HR_LC_SR-WEBP/style.json",
  "raster/naturalearth/NE2_HR_LC_SR_W-WEBP/style.json",
  "raster/naturalearth/NE2_HR_LC-WEBP/style.json",
  "raster/naturalearth/SR_HR-WEBP/style.json",
  "raster/s2maps/2016/style.json",
  "raster/s2maps/2023/style.json",
  "raster/terrarium/terrarium/style.json",
]

await Promise.all(styles.map(async (f) => {
  const data = JSON.parse(await fs.readFile(f))
  const languageFields = [["get", "name:en"]]

  data.layers = data.layers.map(l => {
    if (l.layout?.["text-field"] && [
      'poi_volcano_rank1',
      'poi_peak_rank1',
      'poi_saddle',
      'mountain_peak',
      "natural-point-label",
      "mountain-peak",
      "mountain-peaks-important",
      "mountain-peaks",
    ].includes(l.id)) {
      l.layout["text-field"] = [
        "case",
        ["has", "ele"],
        [
          "case",
          [
            "==",
            ["get", "name"],
            ["coalesce", ...languageFields, ["get", "name"]]
          ],
          [
            "concat",
            ["coalesce", ...languageFields, ["get", "name"]],
            "\n",
            ["to-string", ["round", ["get", "ele"]]],
            "m, ",
            ["to-string", ["round", ["*", ["get", "ele"], 3.28084]]],
            "ft"
          ],
          [
            "format",
            ["coalesce", ...languageFields, ["get", "name"]],
            {},
            "\n",
            {},
            ["get", "name"],
            { "font-scale": 0.8 },
            "\n",
            {},
            ["to-string", ["round", ["get", "ele"]]],
            {},
            "m, ",
            {},
            ["to-string", ["round", ["*", ["get", "ele"], 3.28084]]],
            {},
            "ft",
            {}
          ]
        ],
        [
          "case",
          [
            "==",
            ["get", "name"],
            ["coalesce", ...languageFields, ["get", "name"]]
          ],
          ["coalesce", ...languageFields, ["get", "name"]],
          [
            "format",
            ["coalesce", ...languageFields, ["get", "name"]],
            {},
            "\n",
            {},
            ["get", "name"],
            { "font-scale": 0.8 }
          ]
        ]
      ]
      return l
    }

    if (l.layout?.["text-field"] && ![
      'housenumber',
      'road_shield',
      'highway-shield-non-us',
      'highway-shield-us-interstate',
      'road_shield_us',
      'highway_name_motorway',
      'highway_ref',
      'highway-shield',
      'highway-shield-us-other',
      'highway-shield-tertiary',
      'highway-shield-secondary',
      'highway-shield-primary',
      'highway-shield-motorway',
      'airport_label',
      'airport_gate_label',
      'airport_gate',
      'label-motorway-shield',
      'contour-labels',
      'road-number-shield',
      'highway-shield-other',
      "highway_shield_other",
      "highway_shield_us_other",
      "highway_shield_us_interstate",
      "label-address-housenumber",
      "boundary_country_label_right",
      "boundary_country_label_left",
      "housenumbers",
      "airport_gate_label"
    ].includes(l.id)) {
      l.layout["text-field"] = [
        "case",
        ["==", ["get", "name"], ["coalesce", ...languageFields, ["get", "name"]]],
        ["coalesce", ...languageFields, ["get", "name"]],
        [
          "format",
          ["coalesce", ...languageFields, ["get", "name"]],
          {},
          "\n",
          {},
          ["get", "name"],
          { "font-scale": 0.8 }
        ]
      ]
      return l
    }

    return l
  })
  await fs.writeFile(f, JSON.stringify(data))
}))
